Repository HWO-Yield-Visualizations/yieldplotlib, pull requests merged in 2024-08, with the labels that each got.

#11 chore(main): release 0.1.0
  CHANGELOG.md
Labels: autorelease: pending

#15 feat: Added base SingleInputs class
  src/yieldplotlib/core/single_inputs.py
Labels: enhancement

#18 docs: update developer docs to move away from forking
  docs/user/dev.md
Labels: documentation

#21 feat: Create accessibility checkers
  pyproject.toml
  src/yieldplotlib/accessibility.py
  src/yieldplotlib/core/plot.py
  src/yieldplotlib/util.py
Labels: enhancement

#17 chore(main): release 0.2.0
  CHANGELOG.md
Labels: autorelease: pending
