Repository HWO-Yield-Visualizations/yieldplotlib, pull requests merged in 2025-03, with the labels that each got.

#40 Feature/more yip plots
  src/yieldplotlib/load/yip_directory.py
  src/yieldplotlib/plots/yip_plots.py
Labels: enhancement

#27 chore(main): release 0.3.0
  CHANGELOG.md
Labels: autorelease: pending

#68 HZ completeness refactor with new plotting methods
  src/yieldplotlib/plots/hz_completeness.py
Labels: bug

#73 Remove potentially identifying module names
  docs/tutorials/sample_data/exosims/Example_EXOSIMS.json
  docs/tutorials/sample_data/exosims/csv/Example_EXOSIMS.json
Labels: bug

#71 Pipeline and CLI
  pyproject.toml
  src/yieldplotlib/data/logo.png
  src/yieldplotlib/generate_key_map.py
  src/yieldplotlib/load/ayo/ayo_csv.py
  src/yieldplotlib/pipeline.py
  src/yieldplotlib/plots/comparison_plots.py
  src/yieldplotlib/style/yieldplotlib.mplstyle
  src/yieldplotlib/ypl_cli.py
Labels: enhancement

#67 chore(main): release 0.4.0
  CHANGELOG.md
Labels: autorelease: pending

#79 chore(main): release 0.4.1
  CHANGELOG.md
Labels: autorelease: pending

#70 Documentation work
  .github/workflows/generate_parameters_docs.yml
  README.md
  docs/conf.py
  docs/index.md
  docs/plot_gallery/gallery.md
  docs/plot_gallery/plots/core_throughput.png
  docs/plot_gallery/plots/hz_completeness.png
  docs/plot_gallery/plots/offax_psf_animation.gif
  docs/plot_gallery/plots/stellar_parameters.png
  docs/tutorials/yieldplotlib_tutorial.ipynb
  docs/user/cite.md
  docs/user/installation.md
  docs/user/intro.md
  docs/user/parameters_table.md
  docs/user/ypl_parameters.md
  src/yieldplotlib/accessibility.py
  src/yieldplotlib/generate_docs.py
Labels: documentation

#84 chore(main): release 0.5.0
  CHANGELOG.md
Labels: autorelease: pending

#99 Update Gallery Plots
  .gitignore
  docs/conf.py
  docs/plot_gallery/gallery.md
  docs/plot_gallery/plots/comparative_bar_plot_grouped.png
  docs/plot_gallery/plots/core_throughput_all_curves_cyber.jpeg
  docs/plot_gallery/plots/cyberpunk_core_thruput.png
  docs/plot_gallery/plots/hz_completeness_cyber.png
  docs/plot_gallery/plots/offax_psf_animation.gif
  docs/plot_gallery/plots/plot4_parameter_grid_colored.png
  docs/plot_gallery/plots/star_distance_distribution.png
  src/yieldplotlib/load/ayo/ayo_csv.py
Labels: documentation
